<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.smartcard</groupId>
		<artifactId>smartcard</artifactId>
		<!--<version>0.0.1-SNAPSHOT</version>-->
		<version>1.0.1</version>
	</parent>
	<artifactId>smartcard-core</artifactId>
	<name>Smartcard Core Project</name>
	<description>Smartcard Core Project</description>
	<dependencies>
		<dependency>
		    <groupId>org.bouncycastle</groupId>
		    <artifactId>bcpkix-jdk15on</artifactId>
		    <version>1.50</version>
		</dependency>
		<dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-api</artifactId>
			<version>7.0</version>
			<scope>provided</scope>
			<exclusions>
		        <exclusion>
		            <groupId>dom4j</groupId>
		            <artifactId>dom4j</artifactId>
		        </exclusion>
		        <exclusion>
		           <groupId>org.jboss.logging</groupId>
		           <artifactId>jboss-logging</artifactId>
		        </exclusion>
		    </exclusions>
		</dependency>		
		<dependency>
		    <groupId>commons-beanutils</groupId>
		    <artifactId>commons-beanutils</artifactId>
		    <version>1.9.2</version>
		</dependency>
		<dependency>
		    <groupId>org.apache.poi</groupId>
		    <artifactId>poi</artifactId>
		    <version>3.17</version>
		</dependency>
		<dependency>
		    <groupId>org.apache.poi</groupId>
		    <artifactId>poi-ooxml</artifactId>
		    <version>3.17</version>
		</dependency>
		<dependency>
			<groupId>org.apache.velocity</groupId>
			<artifactId>velocity</artifactId>
			<version>1.7</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
		<dependency>
		    <groupId>io.jsonwebtoken</groupId>
		    <artifactId>jjwt-api</artifactId>
		    <version>0.10.5</version>
		</dependency>
		<dependency>
		    <groupId>io.jsonwebtoken</groupId>
		    <artifactId>jjwt-impl</artifactId>
		    <version>0.10.5</version>
		</dependency>
		<dependency>
		    <groupId>io.jsonwebtoken</groupId>
		    <artifactId>jjwt-jackson</artifactId>
		    <version>0.10.5</version>
		</dependency>
		<dependency>
		    <groupId>com.fasterxml.jackson.core</groupId>
		    <artifactId>jackson-annotations</artifactId>
		    <version>2.9.6</version>
		</dependency>
		<dependency>
		    <groupId>commons-io</groupId>
		    <artifactId>commons-io</artifactId>
		    <version>2.5</version>
		</dependency>
		<dependency>
		    <groupId>com.google.code.gson</groupId>
		    <artifactId>gson</artifactId>
		    <version>2.8.0</version>
		</dependency>
		
		<dependency>
		    <groupId>commons-codec</groupId>
		    <artifactId>commons-codec</artifactId>
		    <version>1.11</version>
		</dependency>
		<dependency>
		    <groupId>commons-net</groupId>
		    <artifactId>commons-net</artifactId>
		    <version>3.6</version>
		</dependency>
		<!-- <dependency>
		    <groupId>com.google.api-client</groupId>
		    <artifactId>google-api-client</artifactId>
		    <version>1.23.0</version>
		</dependency>
		<dependency>
		    <groupId>com.google.oauth-client</groupId>
		    <artifactId>google-oauth-client-jetty</artifactId>
		    <version>1.23.0</version>
		</dependency> -->
    	<dependency>
		    <groupId>com.google.apis</groupId>
		    <artifactId>google-api-services-gmail</artifactId>
		    <version>v1-rev83-1.23.0</version>
		</dependency>
	 	<dependency>
		  <groupId>com.google.firebase</groupId>
		  <artifactId>firebase-admin</artifactId>
		  <version>9.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-jaxrs</artifactId>
			<version>3.0.2.Final</version>
		</dependency>
		<dependency>
		  <groupId>org.jboss.resteasy</groupId>
		    <artifactId>resteasy-jaxb-provider</artifactId>
		  <version>3.0.2.Final</version>
		</dependency>
		<dependency>
		    <groupId>org.jboss.resteasy</groupId>
		    <artifactId>jaxrs-api</artifactId>
		    <version>3.0.2.Final</version>
		</dependency>		
		<dependency>
	        <groupId>com.google.zxing</groupId>
	        <artifactId>core</artifactId>
	        <version>3.3.0</version>
	    </dependency>
	    <dependency>
	        <groupId>com.google.zxing</groupId>
	        <artifactId>javase</artifactId>
	        <version>3.3.0</version>
	    </dependency>
		<dependency>
		    <groupId>org.scannotation</groupId>
		    <artifactId>scannotation</artifactId>
		    <version>1.0.3</version>
		</dependency>
		<dependency>
		    <groupId>org.jboss.resteasy</groupId>
		    <artifactId>resteasy-multipart-provider</artifactId>
		    <version>3.0.14.Final</version>
		    <scope>provided</scope>
		</dependency>
		<dependency>
		  <groupId>com.drewnoakes</groupId>
		  <artifactId>metadata-extractor</artifactId>
		  <version>2.16.0</version>
		</dependency>
	</dependencies>
	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>
</project>
