const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    title: 'KendrickHeller API',
    description: 'API for KendrickHeller generated by swagger-autogen'
  },
  host: 'localhost:3000'
};

const outputFile = './swagger.json';
const routes = ['./src/server.ts'];

swaggerAutogen(outputFile, routes, doc);
